config/routes.rb
N00bPub::Application.routes.draw do
  get "ajax" => "home#ajax"
  get "opchat" => "messages#index"
  resources :messages

  get "faq" => "faq#index"

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]

  match 'p/:url_name' => 'users#show'

end

app/models/daily_stat.rb
class DailyStat < ActiveRecord::Base
  attr_accessible :deaths, :headshots, :hits, :kills, :name, :setinfo_pass, :shots
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessible :name, :time
  validates_uniqueness_of :name, :case_sensitive => false

  # This builds up a data string to insert in Map frequency pie chart
  def self.get_pie_chart_data
    pie_data_string = ""
    all_maps = Map.all
    all_maps.each do |map|
      pie_data_string << "['#{map.name}', #{map.time}], "
    end
    return pie_data_string
  end

  def self.current_map_name
    mp = File.read("/home/nav/cs/cstrike/current_map").split(" ")
    map_name = mp[0].downcase
  end

  def self.current_map_time_started
    mp = File.read("/home/nav/cs/cstrike/current_map").split(" ")
    map_time_started = Time.local(mp[4], mp[5], mp[6], mp[1], mp[2], mp[3])
  end
end

app/models/perma_stat.rb
class PermaStat < ActiveRecord::Base
  attr_accessible :deaths, :headshots, :hits, :kills, :name, :setinfo_pass, :shots
end

app/models/round_stat.rb
class RoundStat < ActiveRecord::Base
  attr_accessible :deaths, :headshots, :hits, :kills, :name, :setinfo_pass, :shots, :team
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :setinfo_pass, :email, :password, :password_confirmation, :remember_me, :url_name
  validates_presence_of :name, :setinfo_pass, :email
  validates_uniqueness_of :name, :setinfo_pass, :email, :case_sensitive => false
  validates_uniqueness_of :url_name, :message => "Please select a different nick. This nick's url-string is already taken"
  #validates :setinfo_pass, :format => { :with => /\A[a-zA-Z]+\z+_/,
  #  :message => "Only letters allowed" }

  before_validation do |user|
    user.url_name = user.name.parameterize.underscore
  end

  after_create do |user|
    new_user = PermaStat.new
    new_user.name = user.name
    new_user.setinfo_pass = user.setinfo_pass
    new_user.save
  end

  after_create do |user|
    new_user = DailyStat.new
    new_user.name = user.name
    new_user.setinfo_pass = user.setinfo_pass
    new_user.save
  end

  after_update :update_account

  after_destroy do |user|
    DailyStat.find_by_setinfo_pass(self.setinfo_pass_was).delete
    PermaStat.find_by_setinfo_pass(self.setinfo_pass_was).delete
  end

  def update_account
    if self.name_changed? or self.email_changed? or self.setinfo_pass_changed? or self.encrypted_password_changed?
      daily_user = DailyStat.find_by_setinfo_pass(self.setinfo_pass_was)
      daily_user.name = self.name
      daily_user.setinfo_pass = self.setinfo_pass
      daily_user.save

      perma_user = PermaStat.find_by_setinfo_pass(self.setinfo_pass_was)
      perma_user.name = self.name
      perma_user.setinfo_pass = self.setinfo_pass
      perma_user.save
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    # This builds up the player_count line chart
    @player_count_array = File.read("/home/nav/player_count_log").split(" ").map(&:to_i)
    @average_count_array = File.read("/home/nav/average_player_count_log").split(" ").map(&:to_i)
    @average_count_array.pop

    require 'tod'
    t = TimeOfDay.new(6)
    @line_data_string = ""
    @player_count_array.fill("null", @player_count_array.count, 720-@player_count_array.count)
    @player_count_array.zip(@average_count_array).each do |c, a|
      @line_data_string << "['#{t.strftime("%I:%M %p")}', #{c}, #{a}],"
      t = t + 120
    end

    # This builds up the map_frequency pie chart
    @pie_data_string = Map.get_pie_chart_data

    @map_name = Map.current_map_name
    @map_time_started = Map.current_map_time_started

    # The messages which appear on the top of home page
    flash.now[:notice] = "New here? Read this if you are <a href=\"/faq\">getting started</a>.".html_safe
    
    # Make the flash messages dissapear if the user is logged in
    if user_signed_in?
      flash.now[:alert] = nil
      flash.now[:notice] = nil
      flash.now[:tip] = nil
    end

    @ts = RoundStat.find_all_by_team(1)
    @cts = RoundStat.find_all_by_team(2)
    @round_stats = RoundStat.all
    @daily_stats = DailyStat.all
    @perma_stats = PermaStat.all

  end

  def ajax
    @no_of_players = RoundStat.all.count
    @map_name = Map.current_map_name
    @map_time_started = Map.current_map_time_started

    @title = "#{@no_of_players}/24 - #{@map_name}"

    @ts = RoundStat.find_all_by_team(1)
    @cts = RoundStat.find_all_by_team(2)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_url_name(params[:url_name])
    redirect_to users_url, :alert => "User doesn't exist or wrong url_name" unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/daily_stats/_index.html.erb
<head>
  <script type="text/javascript" charset="utf-8">
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "hrs-pre": function ( a ) {
    var x = a.split(" ")[0];
    if (a.match(/hrs/)) x = x*60;
    return parseInt( x, 10 );
    },
    
    "hrs-asc": function ( a, b ) {
    return ((a < b) ? -1 : ((a > b) ? 1 : 0));
      },
      
      "hrs-desc": function ( a, b ) {
      return ((a < b) ? 1 : ((a > b) ? -1 : 0));
 	}
 	} );
  </script>
</head>

<table id="daily_stats" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>K:D</th>
      <th>% Hits</th>
      <th>% Headshots</th>
      <th>Time played</th>
    </tr>
  </thead>
  <tbody>
    <% @daily_stats.each do |daily_stat| %>
    <tr>
      <% @perma = PermaStat.find_by_setinfo_pass(daily_stat.setinfo_pass) %>
      <td align="right" width="30%"><%= link_to(daily_stat.name, "p/".concat(daily_stat.name.parameterize.underscore), :class => "popover-with-html", :title =>"<font size=\"3\">#{daily_stat.name}", "data-content" => "</font>
	<font size=\"1\">
	  <table>
	    <thead>
	      <tr>
		<th width=\"40px\">Kills</th>
		<th width=\"40px\">Deaths</th>
		<th width=\"55px\">% Hits</th>
		<th width=\"45px\">% HS</th>
	      </tr>
	    </thead>
	    <tbody>
	      <tr>
		<td>#{@perma.kills}</td>
		<td>#{@perma.deaths}</td>
		<td>#{(100*@perma.hits.to_f/@perma.shots).round(2)}</td>
		<td>#{(100*@perma.headshots.to_f/@perma.shots).round(2)}</td>
	      </tr>
	    </tbody>
	  </table><div align=\"center\">
	    #{@perma.time.round(1)} hrs</div>
	</font>
	") %>
      <td align="right"><%= daily_stat.kills %></td>
      <td align="right"><%= daily_stat.deaths %></td>
      <td align="right"><%= daily_stat.deaths == 0 ? 0 : (daily_stat.kills.to_f/daily_stat.deaths).round(2) %></td>
      <td align="right"><%= daily_stat.shots == 0 ? 0 : (100 * daily_stat.hits.to_f/daily_stat.shots).round(2) %></td>
      <td align="right"><%= daily_stat.shots == 0 ? 0 : (100 * daily_stat.headshots.to_f/daily_stat.shots).round(2) %></td>
      <td align="right"><%= if (time=daily_stat.time)<60 then "#{time} mins" else "#{(time.to_f/60).round(1)} hrs" end %></td>
			    </tr>
    <% end %>
  </tbody>
</table>

app/views/faq/index.html.erb
<h1 ALIGN="center" STYLE="font: 36pt/40pt courier; font-variant: small-caps; ">Frequently asked questions</h1><br>
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#1">
	What's all this about?
      </a>
    </div>
    <div id="1" class="accordion-body collapse">
      <div class="accordion-inner">
	This is a website to display the statistics collected day and night on n00b Pub Server.
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#2">
	Getting Started
      </a>
    </div>
    <div id="2" class="accordion-body collapse in">
      <div class="accordion-inner">
	To participate, you must follow the two steps below in the EXACT order :<br><br>
	<ul>
	  <li>
	<a href="/users/sign_up">Register</a> on the website, selecting a unique "Setinfo pass". This pass will henceforth be used to identify you on the Server and track your scores.<br>
	  </li>
	  <li>
	After registration, you must put the exact pass in your client. Open your userconfig.cfg file (it will be in a location like <i>C:\Program Files\Counter Strike\cstrike\userconfig.cfg</i>, create the file if it does not exist) and add the following line at the end:<br>
	<code>setinfo pass n00b</code><br>
	<i>(replace n00b with the Setinfo pass you registered)</i>
	</li>
	  </ul>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#3">
	If I choose not to register, or if I enter the wrong setinfo pass in my client, will I be kicked from the Server?
      </a>
    </div>
    <div id="3" class="accordion-body collapse">
      <div class="accordion-inner">
	No, registering only makes you eligible for tracking your scores, it does not affect your entry in server. Similiarly, if you enter a wrong setinfo pass, you simply won't be tracked. Nothing else.
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#4">
	Does this mean if I enter another user's setinfo pass in my client, will I be tracked as him?
      </a>
    </div>
    <div id="4" class="accordion-body collapse">
      <div class="accordion-inner">
	Yes, that is intended. The setinfo pass is your only link to the server. It is up to you to keep it safe.
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#5">
	Why does the game lag just before a round starts?
      </a>
    </div>
    <div id="5" class="accordion-body collapse">
      <div class="accordion-inner">
	That's when all players' stats are collected and fed into the database.
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#6">
	Why aren't my daily and all-time scores updating?
      </a>
    </div>
    <div id="6" class="accordion-body collapse">
      <div class="accordion-inner">
	First of all make sure you are being correctly tracked. You can do this by joining the server and checking the '<i>Current Score</i>' tab on the wesite. If you nick is hyperlinked, it means the server is tracking you.<br>
	Also note that daily-score is updated when you disconnect and all-time score is updated from daily-score once a day.
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#7">
	Is the code open?
      </a>
    </div>
    <div id="7" class="accordion-body collapse">
      <div class="accordion-inner">
	Yes! The website's code is available publicly at <a href="https://github.com/Navgeet/n00b-pub">Github</a>. Code contributions are highly appreciated. Bugs and suggestions can be submitted <a href="https://github.com/Navgeet/n00b-pub/issues">here</a>.
      </div>
    </div>
  </div>
</div>

app/views/home/_daily_stats.html.erb
<head>
  <script type="text/javascript" charset="utf-8">
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "hrs-pre": function ( a ) {
    var x = a.split(" ")[0];
    if (a.match(/hrs/)) x = x*60;
    return parseInt( x, 10 );
    },
    
    "hrs-asc": function ( a, b ) {
    return ((a < b) ? -1 : ((a > b) ? 1 : 0));
      },
      
      "hrs-desc": function ( a, b ) {
      return ((a < b) ? 1 : ((a > b) ? -1 : 0));
 	}
 	} );
  </script>
</head>

<table id="daily_table" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>K:D</th>
      <th>% Hits</th>
      <th>% Headshots</th>
      <th>Time played</th>
    </tr>
  </thead>
  <tbody>
    <% @daily_stats.each do |daily_stat| %>
    <% stats = PermaStat.find_by_setinfo_pass(daily_stat.setinfo_pass) %>
    <tr>
      <td align="right" width="30%"><%= render :partial => "popover" , :locals => { :player_name => daily_stat.name, :stats => stats } %></td>
      <td align="right"><%= daily_stat.kills %></td>
      <td align="right"><%= daily_stat.deaths %></td>
      <td align="right"><%= daily_stat.deaths == 0 ? 0 : (daily_stat.kills.to_f/daily_stat.deaths).round(2) %></td>
      <td align="right"><%= daily_stat.shots == 0 ? 0 : (100 * daily_stat.hits.to_f/daily_stat.shots).round(2) %></td>
      <td align="right"><%= daily_stat.shots == 0 ? 0 : (100 * daily_stat.headshots.to_f/daily_stat.shots).round(2) %></td>
      <td align="right"><% if (time = daily_stat.time) < 60 %>
			<%= "#{time} mins" %>
			<% else %>
			<%= "#{(time.to_f/60).round(1)} hrs" %>
			<% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/_line.html.erb
<head>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
    var data = google.visualization.arrayToDataTable([
    ['Time', 'Current traffic', 'Average traffic'],
    <%= @line_data_string %>
    ]);
    
    var options = {
    curveType: "function",
    chartArea: {width: '90%', height: '90%'},
    legend:{position: 'top'},
    series: [{}, {color: 'grey', lineWidth: 1}],
    width: 975, height: 600,
    vAxis: {title: 'Players', baseline: 0, textPosition: 'in'},
    hAxis: {title: 'Time', slantedText: false, maxAlternation: 1, textStyle: {fontSize: 13}, maxTextLines: 1, showTextEvery: 120, viewWindowMode: 'pretty', textPosition: 'in'},

    };
    
    var chart = new google.visualization.LineChart(document.getElementById('graph_line'));
    chart.draw(data, options);
    }
  </script>
</head>

<div id="graph_line"></div>

app/views/home/_map_info.html.erb
<div class="row">
  
  <div class="span2">
    <img id="map_thumb" src="/<%= @map_name %>.jpg" height="130" width="200" style="border:3px ridge black" />
  </div>
  
  <div class="span3">
    <b><font size="3"><%= map_name %></font><br>
      <%= no_of_players %>/24</b> players<br>
    <i>running from <%= distance_of_time_in_words(map_time_started, Time.now) %></i>
  </div>
  
</div>

app/views/home/_perma_stats.html.erb
<head>
  <script type="text/javascript" charset="utf-8">
    jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "time-pre": function ( a ) {
    var x = a.split(" ")[0];
    return parseFloat( x, 10 );
    },
    
    "time-asc": function ( a, b ) {
    return ((a < b) ? -1 : ((a > b) ? 1 : 0));
      },
      
      "time-desc": function ( a, b ) {
      return ((a < b) ? 1 : ((a > b) ? -1 : 0));
 	}
 	} );
  </script>
</head>

<table id="perma_table" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kills</th>
      <th>Deaths</th>
      <th>K:D</th>
      <th>% Hits</th>
      <th>% Headshots</th>
      <th>Time Played</th>
    </tr>
  </thead>
  <tbody>
    <% @perma_stats.each do |perma_stat| %>
    <tr>
      <td align="right" width="30%"><%= link_to perma_stat.name, "p/".concat(perma_stat.name.parameterize.underscore)  %></td>
      <td align="right"><%= perma_stat.kills %></td>
      <td align="right"><%= perma_stat.deaths %></td>
      <td align="right"><%= perma_stat.deaths == 0 ? 0 : (perma_stat.kills.to_f/perma_stat.deaths).round(2) %></td>
      <td align="right"><%= perma_stat.shots == 0 ? 0 : (100 * perma_stat.hits.to_f/perma_stat.shots).round(2) %></td>
      <td align="right"><%= perma_stat.shots == 0 ? 0 : (100 * perma_stat.headshots.to_f/perma_stat.shots).round(2) %></td>
      <td align="right"><%= "#{perma_stat.time.round(1)} hrs" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/_pie.html.erb
<head>
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
    var data = google.visualization.arrayToDataTable([
    ['Map', 'Seconds'],
    <%= @pie_data_string %>
    ]);

    var options = {
    is3D: false,
    width: 900,
    height: 600,
    reverseCategories: true,
    //backgroundColor: { fill:'transparent' },
    chartArea:{left:40,top:30,width:"80%",height:"80%"},
    legend:{alignment: 'center'},
    tooltip:{text: 'percentage'},
    pieSliceTextStyle:{fontSize: 12}
    };

    var chart = new google.visualization.PieChart(document.getElementById('graph_pie'));
    chart.draw(data, options);
    }
  </script>
</head>

<div id="graph_pie"></div>

app/views/home/_popover.html.erb
<%= link_to(player_name, "p/".concat(stats.name.parameterize.underscore), :class => "popover-with-html", :title =>"<font size=\"3\">#{stats.name}", "data-content" => "</font>
	<font size=\"1\">
	  <table>
	    <thead>
	      <tr>
		<th width=\"40px\">Kills</th>
		<th width=\"40px\">Deaths</th>
		<th width=\"55px\">% Hits</th>
		<th width=\"45px\">% HS</th>
	      </tr>
	    </thead>
	    <tbody>
	      <tr>
		<td>#{stats.kills}</td>
		<td>#{stats.deaths}</td>
		<td>#{(100*stats.hits.to_f/stats.shots).round(2)}</td>
		<td>#{(100*stats.headshots.to_f/stats.shots).round(2)}</td>
	      </tr>
	    </tbody>
	  </table><div align=\"center\">
	    #{stats.time.round(1)} hrs</div>
	</font>
	") %>

app/views/home/_round_stats.html.erb
<table id="round_table" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th width="22%">Nick</th>
      <th width="13%">Kils</th>
      <th width="13%">Deaths</th>
      <th width="9%">K:D</th>
      <th width="13%">% Hits</th>
      <th width="13%">% Headshots</th>
      <th width="27%">Time played</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <td colspan="7"><strong><font color="red">Terrorists - <%= ts.count %> players</font></strong></td>
    </tr>
    <% ts.sort_by{|e| -e[:kills]}.each do |player| %>
    <% unless player.setinfo_pass.empty? %>
    <% reg_player = PermaStat.find_by_setinfo_pass(player.setinfo_pass) %>
    <% end %>
    <tr>
      <td>
	<% if reg_player %>
	<%= render :partial => "popover" , :locals => { :player_name => player.name, :stats => reg_player } %>
	<% else %>
	<%= player.name %>
	<% end %>
      </td>
      <td><%= player.kills %></td>
      <td><%= player.deaths %></td>
      <td><%= (player.kills.to_f/player.deaths).round(1) %></td>
      <td><%= (100 * player.hits.to_f/player.shots).round(2) %></td>
      <td><%= (100 * player.headshots.to_f/player.shots).round(2) %></td>
      <td><% if (time = player.time / 60) < 60 %>
	  <%= "#{time} mins" %>
	  <% else %>
	  <%= "#{(time.to_f/60).round(1)} hrs" %>
	  <% end %>
      </td>
    </tr>
    <% end %>
    <tr>
    <td colspan="7" align="center"><strong><font color="blue">Counter Terrorists - <%= cts.count %> players</font></strong></td>
    </tr>
    <% cts.sort_by{|e| -e[:kills]}.each do |player| %>
    <% unless player.setinfo_pass.empty? %>
    <% reg_player = PermaStat.find_by_setinfo_pass(player.setinfo_pass) %>
    <% end %>
    <tr>
      <td>
	<% if reg_player %>
	<%= render :partial => "popover" , :locals => { :player_name => player.name, :stats => reg_player } %>
	<% else %>
	<%= player.name %>
	<% end %>
      </td>
      <td><%= player.kills %></td>
      <td><%= player.deaths %></td>
      <td><%= player.deaths == 0 ? 0 : (player.kills.to_f/player.deaths).round(2) %></td>
      <td><%= (100 * player.hits.to_f/player.shots).round(2) %></td>
      <td><%= (100 * player.headshots.to_f/player.shots).round(2) %></td>
      <td><% if (time = player.time / 60) < 60 %>
	  <%= "#{time} mins" %>
	  <% else %>
	  <%= "#{(time.to_f/60).round(1)} hrs" %>
	  <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/ajax.js.erb
$(document).attr('title', '<%=j @title %>');
$('#map_info').html("<%=j render :partial => "map_info" , :locals => { :map_name => @map_name, :no_of_players => @no_of_players, :map_time_started => @map_time_started } %>");
$('#current').html("<%=j render :partial => "round_stats" , :locals => { :ts => @ts, :cts => @cts } %>");

app/views/home/index.html.erb
<div id="map_info">
  <%= render :partial => "map_info" , :locals => { :map_name => @map_name, :no_of_players => @round_stats.count, :map_time_started => @map_time_started } %>
</div>

<br>
<div class="tabbable tabs-left"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#current" data-toggle="tab">Current score</a></li>
    <li><a href="#daily" data-toggle="tab">Today's scores</a></li>
    <li><a href="#perma" data-toggle="tab">All time scores</a></li>
    <li><a href="#map_freq" data-toggle="tab">Map frequency</a></li>
    <li><a href="#players" data-toggle="tab">Player count</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="current">
      <%= render :partial => "round_stats", :locals => { :ts => @ts, :cts => @cts } %>
    </div>
    <div class="tab-pane" id="daily">
      <div id="daily-div">
	<%= render "daily_stats" %>
      </div>
    </div>
    <div class="tab-pane" id="perma">
      <%= render "perma_stats" %>
    </div>
    <div class="tab-pane" id="map_freq">
      <%= render "pie" %>
    </div>
    <div class="tab-pane" id="players">
      <%= render "line" %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<% if msg %>
<div class="alert alert-<%= if name == :notice then "info" elsif name == :tip then "info" else "error" end %>">
  <a class="close" data-dismiss="alert">&#215;</a>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "n00b Pub", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
  <li class="dropdown" id="welcome">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#welcome">
      Hi! <%= current_user.name %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
	<%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
      </li>
      <li>
	<%= link_to('Edit account', edit_user_registration_path) %>
      </li>
    </ul>
  </li>
  <% else %>
  <li class="dropdown" id="new">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#new">
      New Here?
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
	<%= link_to('Login', new_user_session_path)  %>
      </li>
      <li>
	<%= link_to('Sign up', new_user_registration_path)  %>
      </li>
      <li>
	<%= link_to('faq', faq_path)  %>
      </li>
    </ul>
  </li>
  <% end %>
</ul>

app/views/users/_show.html.erb
<h1>Users#show</h1>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/index.html.erb
<h1 STYLE="font: 27pt/30pt courier; font-variant: small-caps; ">All Users</h1><br>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <% reg_date = user.created_at.strftime("#{user.created_at.day.ordinalize} %B") %>
      <% reg_yr = user.created_at.strftime("%Y") %>
      <%= link_to user.name, "p/".concat(user.name.parameterize.underscore) %> signed up on <%= "#{reg_date}" %>
      <%= ", #{reg_yr}" if reg_yr.to_i > 2012 %>
    </li>
  <% end %>
</ul>